name: Rust CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build Solidity Contracts
        working-directory: crates/contracts
        run: forge build

      - name: Build Workspace
        run: cargo build --workspace --all-targets

      - name: Run Tests
        run: cargo test --workspace

      - name: Run Clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Security Audit
        continue-on-error: true
        run: cargo audit